### PR TITLE
Pointing at newest release of http-proxy-lantern

### PR DESCRIPTION
**Pull request by oxtoacart**
This grabs the analytics changes for getlantern/lantern#3409

### CODE REVIEW

**Comment by aranhoide** [comment]
Shall I deploy this right away?

**Comment by oxtoacart** [comment]
Thanks @aranhoide!  I'll go ahead and deploy today, will be good practice.

On Tuesday, January 26, 2016, aranhoide <notifications@github.com> wrote:

> Shall I deploy this right away?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern_aws/pull/76#issuecomment-175314698>
> .
>


-- 
Cheers,
Ox

-----------------------------------------------------------------------------------------

"I love people who harness themselves, an ox to a heavy cart,
who pull like water buffalo, with massive patience,
who strain in the mud and the muck to move things forward,
who do what has to be done, again and again."

- Marge Piercy

**Comment by aranhoide** [comment]
I already deployed this yesterday to all proxies.  Is there anything new to deploy?

**Comment by oxtoacart** [comment]
Nope, I just hadn't noticed that you already deployed.  It seems to be
running okay, although we're seeing IPs instead of dns names in the stats
(separate thread on that)

Cheers,
Ox

-----------------------------------------------------------------------------------------

"I love people who harness themselves, an ox to a heavy cart,
who pull like water buffalo, with massive patience,
who strain in the mud and the muck to move things forward,
who do what has to be done, again and again."

- Marge Piercy

**Pull request merged**
