### PR TITLE
Azure etc.

### PR DESCRIPTION
**Pull request by aranhoide**
I meant to separate the changes actually required to support Azure in a different PR.  It turns out that they're minimal, quite obvious (except for the path change in the salt state that enables swap space-- which is mostly ineffectual for other providers), and backwards-compatible. 

The other three categories of changes involved here are:
 - removing everything related to wrapper builders (a lot of code was removed, but it wasn't being used anyway so it's a safe change), and
 - upgrade to salt 2014.7.0: some minor things needed to change because of this, and mostly
 - stop using salt states to try and manage Salt itself.  This has always given us more headache than advantages.  Our salt setup is much more vanilla as a result of this.  We use the standard salt bootstrap script to install Salt in first place, and to upgrade salt versions whenever we see fit.

I will just merge this PR myself because I think the usual review discipline would be way more costly than useful here.  Major git archaeology would be required to split the above concerns into separate PRs.  QA by the reviewer would be very time consuming and redundant, since I have deployed and updated a cloudmaster and quite a few minions from this, I'm about to deploy and update many more from this "branch" while testing the cloudfront changes and, afterwards, rebuild most of our infrastructure from scratch.

The fact that we've been deploying to various cloudmasters from feature branches raises the question of whether the feature branch discipline is more helpful than hazardous in the lantern_aws project at this point.  I'm open to coming back to it once things settle a bit, but right now I think we're best served by working from master and pushing/merging frequently.

### CODE REVIEW

**Comment by aranhoide** [comment]
This is just for informal review of whoever wants to, questions, etc.  I'm about to keep banging on this and testing it heavily anyway.

**Comment by aranhoide** [comment]
I'll manually merge this into master so hopefully github keeps this PR around for comments, questions, etc.

**Comment by myleshorton** [comment]
Sounds awesome @aranhoide!

**Comment by aranhoide** [comment]
I don't know whether @myleshorton merged this or github detected my merge from the command line.  Anyway, all this is in master now.

**Comment by myleshorton** [comment]
Yeah GitHub detected it.

On Fri, Jan 23, 2015 at 2:41 PM, aranhoide <notifications@github.com> wrote:

> I don't know whether @myleshorton <https://github.com/myleshorton> merged
> this or github detected my merge from the command line. Anyway, all this is
> in master now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern_aws/pull/35#issuecomment-71279058>.
>



-- 
--
President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Pull request merged**
